server:
  port: 9001

spring:
  application:    name: DEPARTMENT-SERVICE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://sample.microservice.com:8761/eureka/
  instance:
    hostname: sample.microservice.com
